server:
  port: 4040

jwt:
  secret: f5b731cd90578a6aef97a502208e2888338a304264335e601643b1f9705fb3cc
  lifetime: 30m

spring:
  application:
    name: bank
  liquibase:
    change-log: classpath:db/migration/liquibase.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

Что нужно сделать:
  ok Указать настройки подключения к базе данных.
  ok Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
