server:
  port: 4040
spring:
  application:
    name: bank
  liquibase:
    change-log: classpath:db/migration/liquibase.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

Что нужно сделать:
  ok Указать настройки подключения к базе данных.
  ok Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
